#!/bin/csh
###  RAYLEIGH BUILD SCRIPT
###  Usage:  ./build_rayleigh machine_name
###  The Makefile employed is machine dependent
###  See the Makefiles directory for example Makefiles
###  The value of machine_name should correspond to one of the Makefiles
###  in that directory.  Machine name for Makefile is indicated following underscore.

###  For example, to use Makefile_LCD
###  ./build_rayleigh LCD

###  To use Makefile_Pleiades
###  ./build_rayleigh_Pleiades

setenv MACHINE $1
setenv RAYLEIGH_DEBUG $2
mkdir build
cd build
rm *.F90
rm Makefile
cp ../parallel_framework/*.F90 .
cp ../data_structures/*.F90 .
cp ../math_layer/*.F90 .
cp ../IO/*.F90 .
cp ../test_suite/*.F90 .
cp ../physics/*.F90 .
cp ../Makefiles/Makefile_$MACHINE Makefile
cp ../Makefiles/object_list .
make clean
make rayleigh
